export type Word = { emojis: string[]; word: string };

export const WORDS: Word[] = [
  { emojis: ["🦊", "🖥️"], word: "Firefox" },
  { emojis: ["☀️", "🌼"], word: "sunflower" },
  { emojis: ["⭐", "🐟"], word: "starfish" },
  { emojis: ["🧈", "🪰"], word: "butterfly" },
  { emojis: ["🔥", "🪰"], word: "firefly" },
  { emojis: ["🐉", "🪰"], word: "dragonfly" },
  { emojis: ["🌧️", "🏹"], word: "rainbow" },
  { emojis: ["❄️", "👨"], word: "snowman" },
  { emojis: ["🌙", "💡"], word: "moonlight" },
  { emojis: ["💧", "⬇️"], word: "waterfall" },
  { emojis: ["🟢", "🏠"], word: "greenhouse" },
  { emojis: ["🌳", "🏠"], word: "treehouse" },
  { emojis: ["💡", "🏠"], word: "lighthouse" },
  { emojis: ["🌊", "🐴"], word: "seahorse" },
  { emojis: ["🍮", "🐟"], word: "jellyfish" },
  { emojis: ["⚔️", "🐟"], word: "swordfish" },
  { emojis: ["🐱", "🐟"], word: "catfish" },
  { emojis: ["🥇", "🐟"], word: "goldfish" },
  { emojis: ["⚫", "🐦"], word: "blackbird" },
  { emojis: ["👩", "🐞"], word: "ladybug" },
  { emojis: ["📖", "🪱"], word: "bookworm" },
  { emojis: ["⌚", "🐕"], word: "watchdog" },
  { emojis: ["🐂", "🐕"], word: "bulldog" },
  { emojis: ["🔥", "🐕"], word: "hotdog" },
  { emojis: ["🐕", "🏠"], word: "doghouse" },
  { emojis: ["🌲", "🍎"], word: "pineapple" },
  { emojis: ["🧀", "🍰"], word: "cheesecake" },
  { emojis: ["☕", "🍰"], word: "cupcake" },
  { emojis: ["🍳", "🍰"], word: "pancake" },
  { emojis: ["💥", "🌽"], word: "popcorn" },
  { emojis: ["🥩", "⚪"], word: "meatball" },
  { emojis: ["🥛", "🫨"], word: "milkshake" },
  { emojis: ["👩‍🍳", "📖"], word: "cookbook" },
  { emojis: ["🦶", "⚽"], word: "football" },
  { emojis: ["🏠", "🛶"], word: "houseboat" },
  { emojis: ["🌌", "🚢"], word: "spaceship" },
  { emojis: ["🔑", "🪵"], word: "keyboard" },
  { emojis: ["🔑", "🔤"], word: "password" },
  { emojis: ["🦵", "🔝"], word: "laptop" },
  { emojis: ["🧠", "📱"], word: "smartphone" },
  { emojis: ["🧠", "⌚"], word: "smartwatch" },
  { emojis: ["🕸️", "📍"], word: "website" },
  { emojis: ["🏠", "📄"], word: "homepage" },
  { emojis: ["⬇️", "📦"], word: "download" },
  { emojis: ["⬆️", "📦"], word: "upload" },
  { emojis: ["🖥️", "📸"], word: "screenshot" },
  { emojis: ["🗣️", "✉️"], word: "voicemail" },
  { emojis: ["✉️", "📦"], word: "mailbox" },
  { emojis: ["🆕", "📄"], word: "newspaper" },
  { emojis: ["📝", "📖"], word: "notebook" },
  { emojis: ["🦷", "🖌️"], word: "toothbrush" },
  { emojis: ["🛁", "🚪"], word: "bathroom" },
  { emojis: ["🛏️", "🚪"], word: "bedroom" },
  { emojis: ["🏠", "💼"], word: "homework" },
  { emojis: ["👶", "🪑"], word: "babysitter" },
  { emojis: ["🧠", "⛈️"], word: "brainstorm" },
  { emojis: ["❤️", "🥁"], word: "heartbeat" },
  { emojis: ["🧠", "💥"], word: "headache" },
  { emojis: ["🐻", "🦶"], word: "barefoot" },
  { emojis: ["👁️", "🏹"], word: "eyebrow" },
  { emojis: ["👆", "🖨️"], word: "fingerprint" },
  { emojis: ["👄", "🪵"], word: "lipstick" },
  { emojis: ["👂", "💍"], word: "earring" },
  { emojis: ["💪", "🪑"], word: "armchair" },
  { emojis: ["🛞", "🪑"], word: "wheelchair" },
  { emojis: ["☀️", "👓"], word: "sunglasses" },
  { emojis: ["🌧️", "🧥"], word: "raincoat" },
  { emojis: ["🌌", "🪒"], word: "skyscraper" },
  { emojis: ["⬇️", "🌍"], word: "underground" },
  { emojis: ["☀️", "💭"], word: "daydream" },
  { emojis: ["🌙", "🐴"], word: "nightmare" },
  { emojis: ["🍯", "🌙"], word: "honeymoon" },
  { emojis: ["❤️", "🐦"], word: "lovebird" },
  { emojis: ["🧑‍🤝‍🧑", "🚢"], word: "friendship" },
  { emojis: ["👶", "📅"], word: "birthday" },
  { emojis: ["📅", "🔚"], word: "weekend" },
  { emojis: ["🦁", "👑"], word: "Lion King" },
  { emojis: ["⭐", "⚔️"], word: "Star Wars" },
  { emojis: ["🧸", "📖"], word: "Toy Story" },
  { emojis: ["🔎", "🐠"], word: "Finding Nemo" },
  { emojis: ["🦖", "🏞️"], word: "Jurassic Park" },
  { emojis: ["🕷️", "👨"], word: "Spider-Man" },
  { emojis: ["🦇", "👨"], word: "Batman" },
  { emojis: ["🔩", "👨"], word: "Iron Man" },
  { emojis: ["🐜", "👨"], word: "Ant-Man" },
  { emojis: ["🐱", "👩"], word: "Catwoman" },
  { emojis: ["⚫", "🐆"], word: "Black Panther" },
  { emojis: ["🥋", "🐼"], word: "Kung Fu Panda" },
  { emojis: ["👻", "🔫"], word: "Ghostbusters" },
  { emojis: ["🧊", "⏳"], word: "Ice Age" },
  { emojis: ["🏠", "1️⃣"], word: "Home Alone" },
  { emojis: ["🙂", "📖"], word: "Facebook" },
  { emojis: ["👉", "📺"], word: "YouTube" },
  { emojis: ["🥅", "🎬"], word: "Netflix" },
  { emojis: ["💧", "📦"], word: "Dropbox" },
  { emojis: ["🔊", "☁️"], word: "SoundCloud" },
  { emojis: ["▶️", "🚉"], word: "PlayStation" },
  { emojis: ["❓", "📱"], word: "WhatsApp" },
  { emojis: ["🍎", "📺"], word: "Apple TV" },
];

export function normalize(text: string): string {
  return text.toLowerCase().replace(/[\s-]+/g, "");
}

export function createPicker() {
  let pool: Word[] = [];
  return (): Word => {
    if (pool.length === 0) pool = [...WORDS];
    const i = Math.floor(Math.random() * pool.length);
    return pool.splice(i, 1)[0];
  };
}
