export type Word = { emoji: string; word: string }

export const WORDS: Word[] = [
  { emoji: '🍕', word: 'pizza' },
  { emoji: '🍔', word: 'hamburger' },
  { emoji: '🍟', word: 'fries' },
  { emoji: '🌮', word: 'taco' },
  { emoji: '🍣', word: 'sushi' },
  { emoji: '🍩', word: 'donut' },
  { emoji: '🍪', word: 'cookie' },
  { emoji: '🎂', word: 'cake' },
  { emoji: '🍦', word: 'ice cream' },
  { emoji: '🍿', word: 'popcorn' },
  { emoji: '🥑', word: 'avocado' },
  { emoji: '🍓', word: 'strawberry' },
  { emoji: '🍉', word: 'watermelon' },
  { emoji: '🍇', word: 'grapes' },
  { emoji: '🍌', word: 'banana' },
  { emoji: '🍋', word: 'lemon' },
  { emoji: '🥥', word: 'coconut' },
  { emoji: '🥚', word: 'egg' },
  { emoji: '🧀', word: 'cheese' },
  { emoji: '🍯', word: 'honey' },
  { emoji: '🐱', word: 'cat' },
  { emoji: '🐶', word: 'dog' },
  { emoji: '🐰', word: 'rabbit' },
  { emoji: '🐻', word: 'bear' },
  { emoji: '🐼', word: 'panda' },
  { emoji: '🐨', word: 'koala' },
  { emoji: '🦁', word: 'lion' },
  { emoji: '🐯', word: 'tiger' },
  { emoji: '🐘', word: 'elephant' },
  { emoji: '🦒', word: 'giraffe' },
  { emoji: '🐵', word: 'monkey' },
  { emoji: '🐸', word: 'frog' },
  { emoji: '🦉', word: 'owl' },
  { emoji: '🐧', word: 'penguin' },
  { emoji: '🦈', word: 'shark' },
  { emoji: '🐳', word: 'whale' },
  { emoji: '🐬', word: 'dolphin' },
  { emoji: '🐙', word: 'octopus' },
  { emoji: '🦀', word: 'crab' },
  { emoji: '🐌', word: 'snail' },
  { emoji: '🐢', word: 'turtle' },
  { emoji: '🦋', word: 'butterfly' },
  { emoji: '🐝', word: 'bee' },
  { emoji: '🕷️', word: 'spider' },
  { emoji: '🦇', word: 'bat' },
  { emoji: '🦖', word: 'dinosaur' },
  { emoji: '🐉', word: 'dragon' },
  { emoji: '🦄', word: 'unicorn' },
  { emoji: '🦊', word: 'fox' },
  { emoji: '🐺', word: 'wolf' },
  { emoji: '🦌', word: 'deer' },
  { emoji: '🐴', word: 'horse' },
  { emoji: '🐮', word: 'cow' },
  { emoji: '🐷', word: 'pig' },
  { emoji: '🐑', word: 'sheep' },
  { emoji: '🐔', word: 'chicken' },
  { emoji: '🦆', word: 'duck' },
  { emoji: '🐦', word: 'bird' },
  { emoji: '🐠', word: 'fish' },
  { emoji: '🐍', word: 'snake' },
  { emoji: '🔥', word: 'fire' },
  { emoji: '🌧️', word: 'rain' },
  { emoji: '❄️', word: 'snow' },
  { emoji: '🌞', word: 'sun' },
  { emoji: '🌙', word: 'moon' },
  { emoji: '⭐', word: 'star' },
  { emoji: '🌈', word: 'rainbow' },
  { emoji: '⚡', word: 'lightning' },
  { emoji: '🌊', word: 'wave' },
  { emoji: '🌋', word: 'volcano' },
  { emoji: '⛰️', word: 'mountain' },
  { emoji: '🌵', word: 'cactus' },
  { emoji: '🌲', word: 'tree' },
  { emoji: '🍄', word: 'mushroom' },
  { emoji: '🌹', word: 'rose' },
  { emoji: '🌻', word: 'sunflower' },
  { emoji: '🚗', word: 'car' },
  { emoji: '🚀', word: 'rocket' },
  { emoji: '✈️', word: 'plane' },
  { emoji: '🚲', word: 'bicycle' },
  { emoji: '🚢', word: 'boat' },
  { emoji: '🏠', word: 'house' },
  { emoji: '🏰', word: 'castle' },
  { emoji: '👑', word: 'crown' },
  { emoji: '🤖', word: 'robot' },
  { emoji: '👻', word: 'ghost' },
  { emoji: '🎃', word: 'pumpkin' },
  { emoji: '🎈', word: 'balloon' },
  { emoji: '🎁', word: 'gift' },
  { emoji: '🎲', word: 'dice' },
  { emoji: '🎯', word: 'target' },
  { emoji: '🎸', word: 'guitar' },
  { emoji: '🎹', word: 'piano' },
  { emoji: '🥁', word: 'drums' },
  { emoji: '🎺', word: 'trumpet' },
  { emoji: '🎻', word: 'violin' },
  { emoji: '🎤', word: 'microphone' },
  { emoji: '🎧', word: 'headphones' },
  { emoji: '📱', word: 'phone' },
  { emoji: '💻', word: 'laptop' },
  { emoji: '⌚', word: 'watch' },
  { emoji: '💎', word: 'diamond' },
  { emoji: '🔑', word: 'key' },
  { emoji: '☂️', word: 'umbrella' },
  { emoji: '⚽', word: 'soccer' },
  { emoji: '🏀', word: 'basketball' },
  { emoji: '🎾', word: 'tennis' },
  { emoji: '⚾', word: 'baseball' },
  { emoji: '🏈', word: 'football' },
  { emoji: '🧙', word: 'wizard' },
  { emoji: '🏴‍☠️', word: 'pirate' },
  { emoji: '🧜‍♀️', word: 'mermaid' },
  { emoji: '🦸', word: 'superhero' },
  { emoji: '🧟', word: 'zombie' },
  { emoji: '🧛', word: 'vampire' },
  { emoji: '🧚', word: 'fairy' },
  { emoji: '🥷', word: 'ninja' },
]

export function normalize(text: string): string {
  return text.toLowerCase().trim().replace(/\s+/g, ' ')
}

export function createPicker() {
  let pool: Word[] = []
  return (): Word => {
    if (pool.length === 0) pool = [...WORDS]
    const i = Math.floor(Math.random() * pool.length)
    return pool.splice(i, 1)[0]
  }
}